### ISSUE TITLE
Consider closing file handler after using SplFileObject and SplFileInfo

### ISSUE THREAD

**Issue by peter279k** [selective-php/image-type#6]
As title, it seems that the `SplFileObject` and `SplFileInfo` will let them be null after using them are done.

It seems that the `ImageTypeDetector` class uses the `unset` to release the `SplFileObject` variable.

But the `SplFileInfo` variable does not in `ImageTypeDetectorTest` class.

BTW, using the `unset` or assigning `null` is same as closing file handler.

Which one we prefer using in this repository?

**Comment by odan** [comment]
There is a good explaination on [SO](https://stackoverflow.com/a/13667734/1461181).

In a nutshell
* **assigning null**: keeps the variable, is faster then unset, doesn't restore the whole memory
* **unset**: Removes the variable from the symbol table, slower, restores the whole memory

I've used `unset` because I really don't need the variable anymore and I wanted to clean up everything.

Within a test it does't really matter, because the [PHP garbage collector](https://tideways.com/profiler/blog/how-to-optimize-the-php-garbage-collector-usage-to-improve-memory-and-performance) will clean it up anyway.

**Comment by peter279k** [comment]
Closed via current explanation :).
